import type { Metadata } from "next";
import { Lalezar, Mukta, Inter, Reem_Kufi } from "next/font/google";
import "./globals.css";

const lalezarSans = Lalezar({
  weight: "400",
  variable: "--font-lalezar-sans",
  subsets: ["latin"],
});

const muktaSans = Mukta({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-mukta-sans",
  subsets: ["latin"],
});

const interSans = Inter({
  weight: "variable",
  variable: "--font-inter-sans",
});

const reemKufiSans = Reem_Kufi({
  weight: "variable",
  variable: "--font-reemkufi-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sticheii App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lalezarSans.variable} ${muktaSans.variable} ${interSans.variable} ${reemKufiSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
